/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ConfirmEmailRouteImport } from './routes/confirm-email'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppLeadsRouteImport } from './routes/_app/leads'
import { Route as AppKnowledgeRouteImport } from './routes/_app/knowledge'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCampaignsRouteImport } from './routes/_app/campaigns'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api/public/whatsapp-webhook'
import { Route as ApiPublicTwilioWebhookRouteImport } from './routes/api/public/twilio-webhook'
import { Route as ApiPublicFollowupTriggerRouteImport } from './routes/api/public/followup-trigger'
import { Route as ApiPrivateManualFollowupRouteImport } from './routes/api/private/manual-followup'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmEmailRoute = ConfirmEmailRouteImport.update({
  id: '/confirm-email',
  path: '/confirm-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeRoute = AppKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsRoute = AppCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp-webhook',
    path: '/api/public/whatsapp-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTwilioWebhookRoute = ApiPublicTwilioWebhookRouteImport.update({
  id: '/api/public/twilio-webhook',
  path: '/api/public/twilio-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFollowupTriggerRoute = ApiPublicFollowupTriggerRouteImport.update({
  id: '/api/public/followup-trigger',
  path: '/api/public/followup-trigger',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPrivateManualFollowupRoute = ApiPrivateManualFollowupRouteImport.update({
  id: '/api/private/manual-followup',
  path: '/api/private/manual-followup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/confirm-email': typeof ConfirmEmailRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/campaigns': typeof AppCampaignsRoute
  '/dashboard': typeof AppDashboardRoute
  '/knowledge': typeof AppKnowledgeRoute
  '/leads': typeof AppLeadsRoute
  '/settings': typeof AppSettingsRoute
  '/api/public/twilio-webhook': typeof ApiPublicTwilioWebhookRoute
  '/api/public/whatsapp-webhook': typeof ApiPublicWhatsappWebhookRoute
  '/api/public/followup-trigger': typeof ApiPublicFollowupTriggerRoute
  '/api/private/manual-followup': typeof ApiPrivateManualFollowupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/confirm-email': typeof ConfirmEmailRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/campaigns': typeof AppCampaignsRoute
  '/dashboard': typeof AppDashboardRoute
  '/knowledge': typeof AppKnowledgeRoute
  '/leads': typeof AppLeadsRoute
  '/settings': typeof AppSettingsRoute
  '/api/public/twilio-webhook': typeof ApiPublicTwilioWebhookRoute
  '/api/public/whatsapp-webhook': typeof ApiPublicWhatsappWebhookRoute
  '/api/public/followup-trigger': typeof ApiPublicFollowupTriggerRoute
  '/api/private/manual-followup': typeof ApiPrivateManualFollowupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/confirm-email': typeof ConfirmEmailRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/_app/campaigns': typeof AppCampaignsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/knowledge': typeof AppKnowledgeRoute
  '/_app/leads': typeof AppLeadsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/api/public/twilio-webhook': typeof ApiPublicTwilioWebhookRoute
  '/api/public/whatsapp-webhook': typeof ApiPublicWhatsappWebhookRoute
  '/api/public/followup-trigger': typeof ApiPublicFollowupTriggerRoute
  '/api/private/manual-followup': typeof ApiPrivateManualFollowupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/confirm-email'
    | '/onboarding'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/campaigns'
    | '/dashboard'
    | '/knowledge'
    | '/leads'
    | '/settings'
    | '/api/public/twilio-webhook'
    | '/api/public/whatsapp-webhook'
    | '/api/public/followup-trigger'
    | '/api/private/manual-followup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/confirm-email'
    | '/onboarding'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/campaigns'
    | '/dashboard'
    | '/knowledge'
    | '/leads'
    | '/settings'
    | '/api/public/twilio-webhook'
    | '/api/public/whatsapp-webhook'
    | '/api/public/followup-trigger'
    | '/api/private/manual-followup'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/confirm-email'
    | '/onboarding'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/_app/campaigns'
    | '/_app/dashboard'
    | '/_app/knowledge'
    | '/_app/leads'
    | '/_app/settings'
    | '/api/public/twilio-webhook'
    | '/api/public/whatsapp-webhook'
    | '/api/public/followup-trigger'
    | '/api/private/manual-followup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ConfirmEmailRoute: typeof ConfirmEmailRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  ApiPublicTwilioWebhookRoute: typeof ApiPublicTwilioWebhookRoute
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRoute
  ApiPublicFollowupTriggerRoute: typeof ApiPublicFollowupTriggerRoute
  ApiPrivateManualFollowupRoute: typeof ApiPrivateManualFollowupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm-email': {
      id: '/confirm-email'
      path: '/confirm-email'
      fullPath: '/confirm-email'
      preLoaderRoute: typeof ConfirmEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads': {
      id: '/_app/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/knowledge': {
      id: '/_app/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AppKnowledgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaigns': {
      id: '/_app/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AppCampaignsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/whatsapp-webhook': {
      id: '/api/public/whatsapp-webhook'
      path: '/api/public/whatsapp-webhook'
      fullPath: '/api/public/whatsapp-webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twilio-webhook': {
      id: '/api/public/twilio-webhook'
      path: '/api/public/twilio-webhook'
      fullPath: '/api/public/twilio-webhook'
      preLoaderRoute: typeof ApiPublicTwilioWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/followup-trigger': {
      id: '/api/public/followup-trigger'
      path: '/api/public/followup-trigger'
      fullPath: '/api/public/followup-trigger'
      preLoaderRoute: typeof ApiPublicFollowupTriggerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/private/manual-followup': {
      id: '/api/private/manual-followup'
      path: '/api/private/manual-followup'
      fullPath: '/api/private/manual-followup'
      preLoaderRoute: typeof ApiPrivateManualFollowupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppCampaignsRoute: typeof AppCampaignsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppKnowledgeRoute: typeof AppKnowledgeRoute
  AppLeadsRoute: typeof AppLeadsRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCampaignsRoute: AppCampaignsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppKnowledgeRoute: AppKnowledgeRoute,
  AppLeadsRoute: AppLeadsRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ConfirmEmailRoute: ConfirmEmailRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  ApiPublicTwilioWebhookRoute: ApiPublicTwilioWebhookRoute,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRoute,
  ApiPublicFollowupTriggerRoute: ApiPublicFollowupTriggerRoute,
  ApiPrivateManualFollowupRoute: ApiPrivateManualFollowupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
